from detectron2.config import CfgNode as CN

def add_config(cfg):

    cfg.MODEL.SEM_SEG_HEAD.PIXEL_DECODER_NAME = "MaskDINOEncoder"

    cfg.MODEL.ENCODER = CN()
    cfg.MODEL.ENCODER.NUM_CLASSES = 133
    cfg.MODEL.ENCODER.CONVS_DIM = 256
    cfg.MODEL.ENCODER.MASK_DIM = 256
    cfg.MODEL.ENCODER.NORM = "GN"
    cfg.MODEL.ENCODER.IN_FEATURES = [ "res2", "res3", "res4", "res5" ]
    cfg.MODEL.ENCODER.DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES = [ "res2", "res3", "res4", "res5" ]
    cfg.MODEL.ENCODER.COMMON_STRIDE = 4
    cfg.MODEL.ENCODER.TRANSFORMER_ENC_LAYERS = 6
    cfg.MODEL.ENCODER.TOTAL_NUM_FEATURE_LEVELS = 5
    cfg.MODEL.ENCODER.NUM_FEATURE_LEVELS = 3
    cfg.MODEL.ENCODER.FEATURE_ORDER = "low2high"

    cfg.MODEL.DECODER = CN()
    cfg.MODEL.DECODER.NHEADS = 8
    cfg.MODEL.DECODER.DROPOUT = 0.0
    cfg.MODEL.DECODER.DIM_FEEDFORWARD = 2048

    cfg.MODEL.TEXT = CN()
    cfg.MODEL.TEXT.MODEL_NAME = ""
    cfg.MODEL.TEXT.TOKEN_NAME = ""

    cfg.MODEL.TRANSFORMER_DECODER = CN()
    cfg.MODEL.TRANSFORMER_DECODER.NAME = ""
    cfg.MODEL.TRANSFORMER_DECODER.HIDDEN_DIM = 256
    cfg.MODEL.TRANSFORMER_DECODER.NUM_OBJECT_QUERIES = 900
    cfg.MODEL.TRANSFORMER_DECODER.NHEADS = 8
    cfg.MODEL.TRANSFORMER_DECODER.DROPOUT = 0.0
    cfg.MODEL.TRANSFORMER_DECODER.DIM_FEEDFORWARD = 2048
    cfg.MODEL.TRANSFORMER_DECODER.DEC_LAYERS = 9
    cfg.MODEL.TRANSFORMER_DECODER.TOTAL_NUM_FEATURE_LEVELS = 5
    cfg.MODEL.TRANSFORMER_DECODER.MASK_DIM = 256
    cfg.MODEL.TRANSFORMER_DECODER.LEARN_TGT = False

    cfg.MODEL.SAM_WEIGHTS = ""